---
- hosts: workers
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Import Hadoop configuration files
      template:
        src: "../config/datanode/{{ item }}.j2"
        dest: "/usr/local/hadoop/etc/hadoop/{{ item }}"
        owner: hdfs
        group: hadoop
        mode: 0644
      with_items:
        - core-site.xml
        - hdfs-site.xml

    - name: Create working directories
      file:
        path: "{{ item }}"
        group: hadoop
        owner: hdfs
        mode: 0755
        state: directory
      with_items:
        - "{{ hadoop_datanode_path }}"
        - "{{ hadoop_tmp_path }}"
