---
- hosts: namenode
  become: yes

  vars_files:
    - vars.yml

  roles:
    - master-node

  tasks:
    - name: Create HDFS working directories
      file:
        path: "{{ item }}"
        group: hadoop
        owner: hdfs
        mode: 0755
        state: directory
      with_items:
        - "{{ hadoop_namenode_path }}"
        - "{{ hadoop_tmp_path }}"
