---
- hosts: workers
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Create yarn local directory
      file:
        path: "{{ hadoop_home }}/nodemanager"
        owner: yarn
        group: hadoop
        mode: 0755
        state: directory

