---
- hosts: hadoop
  become: yes

  tasks:
    - name: Delete working directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/local/hadoop/namenode
        - /usr/local/hadoop/datanode
        - /usr/local/hadoop/tmp

    - name: Re-create working directories
      file:
        path: "{{ item }}"
        state: directory
        group: hadoop
        owner: hdfs
        mode: 0755
      with_items:
        - /usr/local/hadoop/namenode
        - /usr/local/hadoop/datanode
        - /usr/local/hadoop/tmp
