---
- hosts: masters
  tasks:
    - name: stop hdfs daemons
      shell: /usr/local/hadoop/sbin/stop-dfs.sh
      become_user: hdfs


- hosts: hadoop
  become: yes
  tasks:
    - name: Delete working directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/local/hadoop/namenode
        - /usr/local/hadoop/datanode
        - /usr/local/hadoop/tmp


- hosts: masters
  become: yes
  tasks:
    - name: Re-create working directories on master
      file:
        path: "{{ item }}"
        state: directory
        group: hadoop
        owner: hdfs
        mode: 0755
      with_items:
        - /usr/local/hadoop/namenode
        - /usr/local/hadoop/tmp

- hosts: workers
  become: yes
  tasks:
    - name: Re-create working directories on workers
      file:
        path: "{{ item }}"
        state: directory
        group: hadoop
        owner: hdfs
        mode: 0755
      with_items:
        - /usr/local/hadoop/datanode
        - /usr/local/hadoop/tmp
