---
- name: Prepare /etc/hosts
  shell: echo "127.0.0.1 localhost" > /etc/hosts

- name: Prepare /etc/hostname
  shell: echo "{{ ansible_hostname }}" > /etc/hostname

- name: Make hosts known via /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item }} {{ hostvars[item]['ansible_facts']['hostname'] }}"
    line: "{{ item }} {{ hostvars[item]['ansible_facts']['hostname'] }}"
    state: present
  with_items:
    - "{{ groups['hadoop'] }}"
