# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu1804'
  config.vbguest.auto_update = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false

  config.vm.hostname = 'hadoop'
  config.vm.network :private_network, ip: '192.168.60.2'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '4096'
  end
end
