# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu1804'
  config.vbguest.auto_update = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false

  # default machine configuration
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 512
    vb.cpus = 1
    vb.linked_clone = true
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vb.customize ['modifyvm', :id, '--ioapic', 'on']
  end

  # setup core hadoop nodes
  boxes = [
    { name: 'master1', ip: '192.168.50.2'},
    { name: 'master2', ip: '192.168.50.5'},
    { name: 'worker1', ip: '192.168.50.3'},
    { name: 'worker2', ip: '192.168.50.4'},
    { name: 'edge',    ip: '192.168.50.6'}
  ]

  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network :private_network, ip: opts[:ip]

      config.vm.provision 'shell', inline: <<-SHELL
        sudo ln -s /usr/bin/python3 /usr/bin/python
      SHELL
    end
  end

end
