---
- hosts: workers
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Create working directories
      file:
        path: "{{ item }}"
        group: hadoop
        owner: hdfs
        mode: 0755
        state: directory
      with_items:
        - "{{ hadoop_datanode_path }}"
        - "{{ hadoop_tmp_path }}"
